apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-blue
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: blue
    spec:
      containers:
      - image: gcr.io/<PROJECT ID>/sampleapl:blue
        name: webserver-container
        ports:
        - containerPort: 80
          name: http-server
