apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webserver-canary
spec:
  replicas: 3
  template:
    metadata:
      labels:
        type: webserver
        color: blue
    spec:
      containers:
      - image: us.gcr.io/inbound-rune-devops-gke/webserver:green
        name: webserver-container
        ports:
        - containerPort: 80
          name: http-server
